// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using g181210044_g191210044.Data;

#nullable disable

namespace g181210044_g191210044.Migrations
{
    [DbContext(typeof(SporContext))]
    [Migration("20220822165806_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("g181210044_g191210044.Entity.BlogYazisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BegeniSayisi")
                        .HasColumnType("int");

                    b.Property<int>("BlogYazariId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("YazarId")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogYazariId");

                    b.ToTable("BlogYazisi");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KatilimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Uye");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Uye");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("BlogYazisiId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UyeId")
                        .HasMaxLength(3000)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogYazisiId");

                    b.HasIndex("UyeId");

                    b.ToTable("Yorum");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.Admin", b =>
                {
                    b.HasBaseType("g181210044_g191210044.Entity.Uye");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.BlogYazari", b =>
                {
                    b.HasBaseType("g181210044_g191210044.Entity.Uye");

                    b.HasDiscriminator().HasValue("BlogYazari");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.BlogYazisi", b =>
                {
                    b.HasOne("g181210044_g191210044.Entity.BlogYazari", "BlogYazari")
                        .WithMany("Yazilari")
                        .HasForeignKey("BlogYazariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogYazari");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.Yorum", b =>
                {
                    b.HasOne("g181210044_g191210044.Entity.BlogYazisi", "BlogYazisi")
                        .WithMany("Yorumlar")
                        .HasForeignKey("BlogYazisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("g181210044_g191210044.Entity.Uye", "Uye")
                        .WithMany("YaptigiYorumlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogYazisi");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.BlogYazisi", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.Uye", b =>
                {
                    b.Navigation("YaptigiYorumlar");
                });

            modelBuilder.Entity("g181210044_g191210044.Entity.BlogYazari", b =>
                {
                    b.Navigation("Yazilari");
                });
#pragma warning restore 612, 618
        }
    }
}
